POST http://localhost:3003/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "Example 1",
  "author": "me",
  "url": "/someurl1",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs HTTP/1.1 
content-type: application/json

{
  "title": "Example 2",
  "author": "me",
  "url": "/someurl2",
  "likes": 2
}